development:
  adapter: postgresql
  database: altius_website_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: altius_website_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: altius_website_production
  pool: 5
  timeout: 5000
